### ISSUE TITLE
Translation mistake in french version

### ISSUE THREAD

**Issue by targeex** [mohamedmansour/prayer-times-extension#11]
Dhur is translated "coucher du soleil" wich mean sunset

**Comment by mohamedmansour** [comment]
@targeex  @Logicbloke  what is the correct translation? 

Does this make sense?

```
	"fajr": {
		"message": "L'aube"
	},
	"sunrise": {
		"message": "Lever du soleil"
	},
	"dhuhr": {
		"message": "Crépuscule"
	},
	"asr": {
		"message": "Asr"
	},
	"sunset": {
		"message": "Coucher du soleil"
	},
	"maghrib": {
		"message": "Maghrib"
	},
	"isha": {
		"message": "Isha"
	},
	"midnight": {
		"message": "Minuit"
	},
```

**Comment by Logicbloke** [comment]
I think we should just keep Fajr, Duhr and Asr as is.

**Comment by mohamedmansour** [comment]
@logicbloke thank you, I just did that!

**Comment by mohamedmansour** [comment]
@Logicbloke  @targeex  the extension is updated , y ou can download it from here https://chrome.google.com/webstore/detail/ndmbeogingkjkmmkoomnigifmpajmbkc
