### ISSUE TITLE
Location Map Not Showing on Prayer Times 3.0.2 Chrome 33.0.1707.0 (on 31 stable as well)

### ISSUE THREAD

**Issue by abuaysha** [mohamedmansour/prayer-times-extension#16]
As written in subject
Location Map Not Showing on Prayer Times 3.0.2 on Chrome 33.0.1707.0 (on 31 stable as well) both on Windows 7.

First symptom occur in Chrome 31 latest

Then I thought it was a version issue, then  I upgraded to Chrome 33.0.1707.0 
Condition still the same
In fact, in 33.0.1707.0 , written as follows:
Prayer Times Options (vundefined)

![praytimes](https://f.cloud.github.com/assets/4149014/1588177/08eab08e-524b-11e3-841e-b5d1cdf7ccef.png)

**Comment by mohamedmansour** [comment]
Sorry This will be fixed in #18 @msdousti updated the google key

**Comment by mohamedmansour** [comment]
@abuaysha  it should be working again, you can download it from here https://chrome.google.com/webstore/detail/ndmbeogingkjkmmkoomnigifmpajmbkc
