### ISSUE TITLE
Extension stopped working in Chrome v. 35

### ISSUE THREAD

**Issue by savafa** [mohamedmansour/prayer-times-extension#17]
Hi,
The extension has stopped counting down and therefore playing the Adhan when Google Chrome has updated to version 35. The countdown goes until it reaches 1 minutes left to prayer time and then stops. Can you fix this or let me know what are the other Shia option doing similar thing?

**Comment by mohamedmansour** [comment]
@savafa  @itsazzad  I have deployed the fixed version, it should work!  You can download it from here https://chrome.google.com/webstore/detail/ndmbeogingkjkmmkoomnigifmpajmbkc
